#!/bin/bash

options=(
  style=round
  width=16.0
  hidpi=on
  active_color="gradient(top_right=0xffbf7775,bottom_left=0xff81fdd4)"
  inactive_color="gradient(top_right=0x40bf7775,bottom_left=0x405e8f97)"
)

borders "${options[@]}"
